In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/brevo_import.csv")

df.head()

,EMAIL,FIRSTNAME,SMS,OWNER,REGISTER_DATE,LEAD_SOURCE,COURSE,LEAD_TYPE,SCHOLARSHIP,SEGMENT
0,anhmol2k5@gmail.com,Nguyễn Anh Tuấn,NaN,Mr. KhangNNM,6/30/2026 13:07,Event hợp tác với AIESEC tháng 12/2025,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN
1,tramanhnguyen1226@gmail.com,Nguyễn Trâm Anh,NaN,Mr. KhangNNM,6/30/2026 13:07,Event hợp tác với AIESEC tháng 12/2025,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN
2,n.duylong145@gmail.com,Nguyễn Duy Long,NaN,Mr. KhangNNM,6/30/2026 13:07,Event hợp tác với AIESEC tháng 12/2025,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN
3,hoangnama2k58@gmail.com,Hoàng Xuân Nam,NaN,Mr. KhangNNM,6/30/2026 13:07,Event hợp tác với AIESEC tháng 12/2025,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN
4,Buidanghoangyen@gmail.com,Bùi Đặng Hoàng Yến,NaN,Mr. KhangNNM,6/30/2026 13:07,Event hợp tác với AIESEC tháng 12/2025,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN

In [3]:
print(df.shape)

df.info()

df.describe(include="all")

(968, 10)
<class 'pandas.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EMAIL          967 non-null    str
 1   FIRSTNAME      968 non-null    str
 2   SMS            940 non-null    float64
 3   OWNER          968 non-null    str
 4   REGISTER_DATE  968 non-null    str
 5   LEAD_SOURCE    968 non-null    str
 6   COURSE         968 non-null    str
 7   LEAD_TYPE      867 non-null    str
 8   SCHOLARSHIP    968 non-null    bool
 9   SEGMENT        0 non-null      float64
dtypes: bool(1), float64(2), str(7)
memory usage: 69.1 KB

,EMAIL,FIRSTNAME,SMS,OWNER,REGISTER_DATE,LEAD_SOURCE,COURSE,LEAD_TYPE,SCHOLARSHIP,SEGMENT
count,967,968,9.400000e+02,968,968,968,968,867,968,0.0
unique,920,882,NaN,1,4,14,7,3,2,NaN
top,quannhao2k6@gmail.com,Nguyễn Phương Anh,NaN,Mr. KhangNNM,6/30/2026 13:07,Sự kiện với các CLB,Business Intelligence (BI),Loại 3 - Cần nhiều thời gian,False,NaN
freq,3,4,NaN,968,839,307,537,571,503,NaN
mean,NaN,NaN,8.458661e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,2.813759e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,3.879201e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,3.822258e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,8.622972e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,9.435194e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,8.477813e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df.isnull().sum())
print(df.duplicated().sum())
print(df["EMAIL"].duplicated().sum())

EMAIL              1
FIRSTNAME          0
SMS               28
OWNER              0
REGISTER_DATE      0
LEAD_SOURCE        0
COURSE             0
LEAD_TYPE        101
SCHOLARSHIP        0
SEGMENT          968
dtype: int64
11
47

In [ ]:
df["COURSE"].value_counts()

COURSE
Business Intelligence (BI)       537
Generative AI (GenAI)            217
Business Analyst                 101
Data Analytics (DA)               60
AI Agent                          33
AI for work                       17
Data Analytics (DA), AI Agent      3
Name: count, dtype: int64

In [7]:
df["LEAD_SOURCE"].value_counts()

LEAD_SOURCE
Sự kiện với các CLB                                            307
Lớp Công nghệ số của VNU                                       217
Event hợp tác với AIESEC tháng 12/2025                         185
Sự kiện tranh biện tiếng Trung với FTU tháng 5/2026             98
Sự kiện Data For Impact tháng 5/2026 tại HV Ngân hàng           49
Fanpage Facebook                                                44
Nhóm cộng đồng trên Facebook                                    33
Fanpage Facebook, Nhóm cộng đồng trên Facebook                  11
Sự kiện Banker Tomorrow tại BAV tháng 5/2026                    11
Tư vấn viên                                                      7
Fanpage Facebook, Nhóm cộng đồng trên Facebook, Tư vấn viên      3
Nhóm zalo                                                        1
Tư vấn viên,                                                     1
Email                                                            1
Name: count, dtype: int64

In [8]:
df["LEAD_TYPE"].value_counts()

LEAD_TYPE
Loại 3 - Cần nhiều thời gian    571
Loại 2 - Trung bình             285
Loại 1 - Tốt nhất                11
Name: count, dtype: int64

In [9]:
df["SCHOLARSHIP"].value_counts()

SCHOLARSHIP
False    503
True     465
Name: count, dtype: int64

In [11]:
df["COURSE_COUNT"] = (
    df["COURSE"]
    .fillna("")
    .str.split(",")
    .apply(len)
)
df["COURSE_COUNT"].value_counts()

COURSE_COUNT
1    965
2      3
Name: count, dtype: int64

In [ ]:
df["MULTI_COURSE"] = df["COURSE_COUNT"] > 1

df["MULTI_COURSE"].value_counts()

MULTI_COURSE
False    965
True       3
Name: count, dtype: int64

: